# マップ圧縮コード

## マップを入手

https://labo-code.com/python/image-analysis/image-to-list/

In [1]:
from PIL import Image
import numpy as np
import cv2

img = Image.open('tsudanuma.pgm')

width, height = img.size

image_array = np.empty((height, width), dtype = int)

for y in range(height):
    for x in range(width):
        image_array[y][x] = img.getpixel((x, y))

## マップのサイズ入力

In [2]:
m = 6240
n = 4000

## 圧縮倍率を設定

In [3]:
z = 40

## マップの行列を入手

https://www.sejuku.net/blog/75248

In [4]:
a = image_array
print(a)

[[205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 ...
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]]


## z列の行列に変換

https://note.nkmk.me/python-list-ndarray-1d-to-2d/

In [5]:
b = a.reshape(-1, z)
print(b)

[[205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 ...
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]]


## 行ごとの最小値を求める

https://deepage.net/features/numpy-min.html

In [6]:
c = np.amin(b, axis=1)
print(c)

[205 205 205 ... 205 205 205]


## 列が1/zの形にする

In [7]:
x1 = int(m/z)
d = c.reshape(-1, x1)
print(d)

[[205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 ...
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]]


## 転置する

https://note.nkmk.me/python-numpy-transpose/

In [8]:
e = d.T
print(e)

[[205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 ...
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]]


## 繰り返し

In [9]:
f = e.reshape(-1, z)
g = np.amin(f, axis=1)
y1 = int(n/z)
h = g.reshape(-1, y1)
i = h.T
print(i)

[[205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 ...
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]
 [205 205 205 ... 205 205 205]]


## マップを保存する

https://tomokichi.blog/%E3%80%90python%E3%80%91%E5%8A%A0%E5%B7%A5%E3%81%97%E3%81%9F%E7%94%BB%E5%83%8F%E3%82%92%E4%BF%9D%E5%AD%98%E3%81%97%E3%81%A6%E3%81%BF%E3%82%88%E3%81%86/

In [10]:
cv2.imwrite('new.pgm',i)

True